Updating search views inside i88n_patterns.
Since django 1.10 no support for views as string, it will fail with TypeError.
-
raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().
-